@startuml "Manage categories"

left to right direction
actor User
rectangle Application {
    User --> (Manage categories)
    (Manage categories) .> (Authentication) : include
    (Add category) .> (Manage categories) : extends
    (Manage categories) <.. (Edit expense) : extends
    (Add category) ..> (Enter category info) : include
    (Edit expense) .> (Enter category info) : include
    User --> (Show planning)
}


@enduml