"""Add user table

Revision ID: 271e6e471e21
Revises:
Create Date: 2022-04-18 22:06:30.633979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271e6e471e21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('first_name', sa.Unicode(), nullable=False),
        sa.Column('last_name', sa.Unicode(), nullable=False),
        sa.Column('email', sa.Unicode(), nullable=False),
        sa.Column('password_hash', sa.Unicode(), nullable=False),
        sa.Column('creation_date', sa.DateTime(), nullable=True),
        sa.Column('update_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
